"use strict"

/* global mocha */

/** * Note: this is an autogenerated file, and edits won't be retained. If you
 * want to modify this file's contents, please make the relevant changes in
 * scripts/generate-browser-entry.js
 */
require("../test/add.js")
require("../test/assertion-error.js")
require("../test/assertions/base.js")
require("../test/assertions/computation.js")
require("../test/assertions/deep-equal.js")
require("../test/assertions/has-keys.js")
require("../test/assertions/includes.js")
require("../test/assertions/type.js")
require("../test/cli/args.js")
require("../test/cli/common.js")
require("../test/cli/e2e.js")
require("../test/cli/loader.js")
require("../test/cli/run.js")
require("../test/cli/util.js")
require("../test/core/async-behavior.js")
require("../test/core/basic.js")
require("../test/core/iterators.js")
require("../test/core/reporters.js")
require("../test/core/safety.js")
require("../test/core/selection.js")
require("../test/core/slow.js")
require("../test/core/timeouts.js")
require("../test/define.js")
require("../test/do.js")
require("../test/reporter/spec.js")
require("../test/reporter/tap.js")
require("../test/wrap.js")

mocha.run()
